# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twomenu',
            old_name='sub_menu2_id',
            new_name='tm_id',
        ),
        migrations.RemoveField(
            model_name='twomenu',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='twomenu',
            name='is_active',
        ),
    ]
