# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='order',
            field=models.ForeignKey(db_column='oid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order', verbose_name='商品ID'),
        ),
    ]
